#!/bin/sh

case "$ARCH_NAME" in
  x86)
    ~/droid/android-ndk/default-x86-toolchain/bin/i686-linux-android-strip "$@"
    ;;
  arm)
    ~/droid/android-ndk/default-arm-toolchain/bin/arm-linux-androideabi-strip "$@"
    ;;
  mips)
    ~/droid/android-ndk/default-mips-toolchain/bin/mipsel-linux-android-strip "$@"
    ;;
esac
